// <auto-generated />
using System;
using FikirHavuzu.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FikirHavuzu.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904114340_AddSeedUsersAndIdeas")]
    partial class AddSeedUsersAndIdeas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mevcut veya yeni ürünlere yönelik geliştirme fikirleri",
                            IsActive = true,
                            Name = "Ürün İyileştirme"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Müşteri ve çalışan hizmet kalitesini artırıcı öneriler",
                            IsActive = true,
                            Name = "Hizmet Geliştirme"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Şirket içi operasyonel süreçleri hızlandıran inovatif fikirler",
                            IsActive = true,
                            Name = "Süreç & Verimlilik"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Diğer kategorilere uymayan her türlü inovatif fikir",
                            IsActive = true,
                            Name = "Diğer"
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<int>("EvaluatorUserId")
                        .HasColumnType("int");

                    b.Property<int>("IdeaId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatorUserId");

                    b.HasIndex("IdeaId");

                    b.ToTable("Evaluations");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            ApprovedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Harika bir yenilikçi proje, dijitalleşme vizyonumuza son derece uygun.",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Decision = 1,
                            EvaluatorUserId = 1,
                            IdeaId = 101,
                            Score = 95,
                            Status = 1
                        },
                        new
                        {
                            Id = 102,
                            ApprovedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Sürdürülebilirlik ve yeşil ofis hedeflerimiz açısından örnek bir çalışma.",
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Decision = 1,
                            EvaluatorUserId = 1,
                            IdeaId = 102,
                            Score = 90,
                            Status = 1
                        },
                        new
                        {
                            Id = 103,
                            ApprovedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Gıda ve kaynak israfını önleyecek çok pratik bir uygulama.",
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Decision = 1,
                            EvaluatorUserId = 1,
                            IdeaId = 103,
                            Score = 88,
                            Status = 1
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntendedBenefit")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Ideas");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7/24 hizmet veren, sıkça sorulan soruları otomatik yanıtlayan LLM tabanlı asistan.",
                            IntendedBenefit = "Müşteri memnuniyetini artırmak ve destek talebi yanıt sürelerini %40 kısaltmak.",
                            IsEdited = false,
                            Status = 4,
                            Title = "Yapay Zeka Destekli Müşteri Destek Asistanı",
                            UserId = 101
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Departman bazlı kaynak tüketimini anlık analiz eden ve tasarruf hedefi koyan dijital gösterge paneli.",
                            IntendedBenefit = "Sürdürülebilirlik hedeflerini görünür kılmak ve kağıt/enerji israfını azaltmak.",
                            IsEdited = false,
                            Status = 4,
                            Title = "Şirket İçi Karbon Ayak İzi ve Sıfır Atık Takip Paneli",
                            UserId = 102
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Çalışanların ertesi gün yemek tercihlerini önceden bildirdiği mobil anket ve takip arayüzü.",
                            IntendedBenefit = "Yemekhane gıda israfını engellemek, günlük porsiyon planlamasını veriye dayalı yapmak.",
                            IsEdited = false,
                            Status = 4,
                            Title = "Yemekhane Menü Seçimi ve İsraf Önleme Mobil Uygulaması",
                            UserId = 105
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Git commit ve PR işlemlerinde statik kod analizi yapan otomasyon botu.",
                            IntendedBenefit = "Yazılım geliştirme süreçlerinde kod kalitesini artırmak ve zafiyetleri erken tespit etmek.",
                            IsEdited = false,
                            Status = 2,
                            Title = "Otomatik Kod İnceleme ve Güvenlik Taraması CI/CD Botu",
                            UserId = 103
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Çalışanlar arası güvenli, süre kısıtlamalı ve erişim loglu dosya paylaşım ortamı.",
                            IntendedBenefit = "Hassas kurum verilerinin güvenliğini uçtan uca şifreleme ile korumak.",
                            IsEdited = false,
                            Status = 2,
                            Title = "Zero-Trust Mimarili Şirket İçi Dosya Paylaşım Kasası",
                            UserId = 104
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.IdeaDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("IdeaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.ToTable("IdeaDocuments");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.IdeaEditHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdeaId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.HasIndex("UserId");

                    b.ToTable("IdeaEditHistories");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdeaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kullanıcı ekleme, güncelleme ve pasife alma yetkisi",
                            Name = "UserManagement"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fikir ve önerileri değerlendirme ve puanlama yetkisi",
                            Name = "IdeaEvaluation"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kullanıcılara sistem yetkilerini atama ve kaldırma yetkisi",
                            Name = "PermissionManagement"
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordChangeRequired")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TCNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("TCNo")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@fikirhavuzu.com",
                            FirstName = "Sistem",
                            IsActive = true,
                            IsPasswordChangeRequired = false,
                            LastName = "Yöneticisi",
                            PasswordHash = "$2a$11$jsStJH8UNbA.VY5W2YC2OulejfCal326xhzuQhYYp0EnYsLkLyqVO",
                            PasswordSalt = "STATIC_ADMIN_SALT",
                            PhoneNumber = "05550000000",
                            RegistrationNumber = "adm001",
                            TCNo = "11111111111"
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mehmet.yilmaz@fikirhavuzu.com",
                            FirstName = "Mehmet",
                            IsActive = true,
                            IsPasswordChangeRequired = false,
                            LastName = "Yılmaz",
                            PasswordHash = "$2a$11$jsStJH8UNbA.VY5W2YC2OulejfCal326xhzuQhYYp0EnYsLkLyqVO",
                            PasswordSalt = "STATIC_SALT",
                            PhoneNumber = "05320000001",
                            RegistrationNumber = "PER260901001",
                            TCNo = "22222222221"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ayse.kaya@fikirhavuzu.com",
                            FirstName = "Ayşe",
                            IsActive = true,
                            IsPasswordChangeRequired = false,
                            LastName = "Kaya",
                            PasswordHash = "$2a$11$jsStJH8UNbA.VY5W2YC2OulejfCal326xhzuQhYYp0EnYsLkLyqVO",
                            PasswordSalt = "STATIC_SALT",
                            PhoneNumber = "05320000002",
                            RegistrationNumber = "PER260901002",
                            TCNo = "22222222222"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.demir@fikirhavuzu.com",
                            FirstName = "Ali",
                            IsActive = true,
                            IsPasswordChangeRequired = false,
                            LastName = "Demir",
                            PasswordHash = "$2a$11$jsStJH8UNbA.VY5W2YC2OulejfCal326xhzuQhYYp0EnYsLkLyqVO",
                            PasswordSalt = "STATIC_SALT",
                            PhoneNumber = "05320000003",
                            RegistrationNumber = "PER260901003",
                            TCNo = "22222222223"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zeynep.celik@fikirhavuzu.com",
                            FirstName = "Zeynep",
                            IsActive = true,
                            IsPasswordChangeRequired = false,
                            LastName = "Çelik",
                            PasswordHash = "$2a$11$jsStJH8UNbA.VY5W2YC2OulejfCal326xhzuQhYYp0EnYsLkLyqVO",
                            PasswordSalt = "STATIC_SALT",
                            PhoneNumber = "05320000004",
                            RegistrationNumber = "PER260901004",
                            TCNo = "22222222224"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mustafa.sahin@fikirhavuzu.com",
                            FirstName = "Mustafa",
                            IsActive = true,
                            IsPasswordChangeRequired = false,
                            LastName = "Şahin",
                            PasswordHash = "$2a$11$jsStJH8UNbA.VY5W2YC2OulejfCal326xhzuQhYYp0EnYsLkLyqVO",
                            PasswordSalt = "STATIC_SALT",
                            PhoneNumber = "05320000005",
                            RegistrationNumber = "PER260901005",
                            TCNo = "22222222225"
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elif.ozturk@fikirhavuzu.com",
                            FirstName = "Elif",
                            IsActive = true,
                            IsPasswordChangeRequired = false,
                            LastName = "Öztürk",
                            PasswordHash = "$2a$11$jsStJH8UNbA.VY5W2YC2OulejfCal326xhzuQhYYp0EnYsLkLyqVO",
                            PasswordSalt = "STATIC_SALT",
                            PhoneNumber = "05320000006",
                            RegistrationNumber = "PER260901006",
                            TCNo = "22222222226"
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "burak.aydin@fikirhavuzu.com",
                            FirstName = "Burak",
                            IsActive = true,
                            IsPasswordChangeRequired = false,
                            LastName = "Aydın",
                            PasswordHash = "$2a$11$jsStJH8UNbA.VY5W2YC2OulejfCal326xhzuQhYYp0EnYsLkLyqVO",
                            PasswordSalt = "STATIC_SALT",
                            PhoneNumber = "05320000007",
                            RegistrationNumber = "PER260901007",
                            TCNo = "22222222227"
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "seda.arslan@fikirhavuzu.com",
                            FirstName = "Seda",
                            IsActive = true,
                            IsPasswordChangeRequired = false,
                            LastName = "Arslan",
                            PasswordHash = "$2a$11$jsStJH8UNbA.VY5W2YC2OulejfCal326xhzuQhYYp0EnYsLkLyqVO",
                            PasswordSalt = "STATIC_SALT",
                            PhoneNumber = "05320000008",
                            RegistrationNumber = "PER260901008",
                            TCNo = "22222222228"
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emre.yildiz@fikirhavuzu.com",
                            FirstName = "Emre",
                            IsActive = true,
                            IsPasswordChangeRequired = false,
                            LastName = "Yıldız",
                            PasswordHash = "$2a$11$jsStJH8UNbA.VY5W2YC2OulejfCal326xhzuQhYYp0EnYsLkLyqVO",
                            PasswordSalt = "STATIC_SALT",
                            PhoneNumber = "05320000009",
                            RegistrationNumber = "PER260901009",
                            TCNo = "22222222229"
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrantedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrantedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrantedByUserId = 1,
                            PermissionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrantedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrantedByUserId = 1,
                            PermissionId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrantedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GrantedByUserId = 1,
                            PermissionId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Evaluation", b =>
                {
                    b.HasOne("FikirHavuzu.Entity.Entities.User", "EvaluatorUser")
                        .WithMany("Evaluations")
                        .HasForeignKey("EvaluatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FikirHavuzu.Entity.Entities.Idea", "Idea")
                        .WithMany("Evaluations")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluatorUser");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Idea", b =>
                {
                    b.HasOne("FikirHavuzu.Entity.Entities.Category", "Category")
                        .WithMany("Ideas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FikirHavuzu.Entity.Entities.User", "User")
                        .WithMany("Ideas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.IdeaDocument", b =>
                {
                    b.HasOne("FikirHavuzu.Entity.Entities.Idea", "Idea")
                        .WithMany("Documents")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.IdeaEditHistory", b =>
                {
                    b.HasOne("FikirHavuzu.Entity.Entities.Idea", "Idea")
                        .WithMany("EditHistories")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FikirHavuzu.Entity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Notification", b =>
                {
                    b.HasOne("FikirHavuzu.Entity.Entities.Idea", "Idea")
                        .WithMany("Notifications")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FikirHavuzu.Entity.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.UserPermission", b =>
                {
                    b.HasOne("FikirHavuzu.Entity.Entities.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FikirHavuzu.Entity.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FikirHavuzu.Entity.Entities.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrantedByUser");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Category", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Idea", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("EditHistories");

                    b.Navigation("Evaluations");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.User", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Ideas");

                    b.Navigation("Notifications");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
