const fs = require('fs');

const trPath = 'C:/Users/pc/OneDrive/Masaüstü/FikirHavuzu/FikirHavuzu.Client/public/locales/tr/common.json';
const enPath = 'C:/Users/pc/OneDrive/Masaüstü/FikirHavuzu/FikirHavuzu.Client/public/locales/en/common.json';

const tr = JSON.parse(fs.readFileSync(trPath, 'utf8'));
const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

tr.showcase = {
  title: '🌟 Pırıltılı Fikirler Vitrini',
  description: 'Kurum çalışanları tarafından önerilen ve süreçlerimize başarıyla uygulanan parlak inovasyon projeleri.',
  totalIdeas: 'Toplam {count} Pırıltılı Fikir',
  awardTitle: 'Yılın İnovatörleri Ödül Programı',
  awardDescription: 'Her yıl sonunda podyumdaki ilk 3 personelimiz <strong>"Yılın İnovatörü"</strong> seçilir. Dereceye girenlere, o dönemin dinamiklerine ve çalışanın kendi tercihlerine göre esneklik gösterebilen sürpriz motivasyon ödülleri (hediye çeki, ekstra izin vb.) sunulur.',
  podiumTitle: '🏆 İnovasyon Liderlik Podyumu',
  podiumInfoTooltip: 'Puanlama & Sıralama Nasıl Hesaplanır?',
  podiumSubTitle: '(İnovasyon Puanı, Jüri Puanı & Yönetici Tercihi)',
  you: '(Siz)',
  points: 'Puan',
  juryScoreLabel: 'Jüri:',
  showAllRanking: 'Tüm Sıralamayı Göster (Toplam {count} Kişi)',
  searchPlaceholder: 'Proje başlığı veya çalışan ara...',
  allCategories: 'Tüm Kategoriler',
  clearFilters: 'Filtreleri Temizle',
  noMatchTitle: 'Aramanızla Eşleşen Pırıltılı Fikir Bulunamadı',
  noMatchDesc: 'Vitrinin ışıkları kapalı çünkü henüz hayata geçen bir \'Pırıltılı Fikir\' yok veya aramanızla eşleşen sonuç bulunamadı.',
  newIdeaBtn: 'Yeni Fikir Ekle',
  otherCategory: 'Diğer',
  glitteringBadge: 'Pırıltılı Fikir (+150 Puan)',
  juryScoreBadge: 'Jüri Puanı: {score}/100',
  detailBtn: 'Detay',
  benefitLabel: '🎯 Sağlanan Kurumsal Fayda:',
  guideTitle: 'Puanlama Rehberi',
  guideInnovationTitle: 'İnovasyon Puanı Nedir?',
  guideInnovationDesc1: '• <strong>Olumlu Fikir:</strong> Hakemden 50+ alan her onaylı fikir için <strong>+50 Puan</strong>.',
  guideInnovationDesc2: '• <strong>Pırıltılı Fikir:</strong> Hayata geçip vitrine çıkan fikir için <strong>+100 Ekstra Puan</strong> *(Fikir başına toplam 150 Puan)*.',
  guideJuryTitle: 'Jüri Puanı Nedir?',
  guideJuryDesc: 'Fikir Koordinatörlerinin fikirlere verdiği 0-100 arasındaki gerçek değerlendirme notlarının toplamıdır.',
  guideRuleTitle: '3 Kademeli Sıralama & Eşitlik Bozma Kuralı:',
  guideRule1: '<strong>Toplam İnovasyon Puanı</strong> en yüksek olan çalışan öne geçer.',
  guideRule2: 'Puanlar eşitse, <strong>Hakem Jüri Puanları Toplamı</strong> yüksek olan öne geçer.',
  guideRule3: 'Jüri puanları da eşitse, <strong>Yönetici Tercihi</strong> ile lider belirlenir.',
  leaderboardTitle: 'Genel İnovasyon Liderlik Sıralaması',
  rankCol: 'Sıra',
  employeeCol: 'Çalışan',
  ideaCountCol: 'Fikir Sayısı',
  juryScoreCol: 'Jüri Notu',
  innovationScoreCol: 'İnovasyon Puanı',
  ideaCountBadge: '{count} Fikir',
  pointsBadge: '{points} Puan',
  sortNewest: '📅 En Yeni Eklenenler',
  sortHighest: '⭐ En Yüksek Jüri Puanı',
  sortTitle: '🔤 Başlığa Göre (A-Z)',
  fetchError: 'Vitrin verileri yüklenirken hata:',
  hiddenUser: '🔒 Gizli Katılımcı',
  innovationLeader: '👑 İnovasyon Lideri',
  glitteringInnovator: '🌟 Pırıltılı İnovatör',
  innovativeThinker: '✨ İnovatif Düşünür'
};

en.showcase = {
  title: '🌟 Glittering Ideas Showcase',
  description: 'Brilliant innovation projects proposed by employees and successfully implemented in our processes.',
  totalIdeas: 'Total {count} Glittering Ideas',
  awardTitle: 'Innovators of the Year Award Program',
  awardDescription: 'At the end of each year, the top 3 employees on the podium are selected as <strong>"Innovators of the Year"</strong>. Winners are offered surprise motivational awards (gift vouchers, extra leave, etc.) that can vary depending on the dynamics of the period and the employee\'s own preferences.',
  podiumTitle: '🏆 Innovation Leadership Podium',
  podiumInfoTooltip: 'How is Scoring & Ranking Calculated?',
  podiumSubTitle: '(Innovation Score, Jury Score & Manager\'s Choice)',
  you: '(You)',
  points: 'Points',
  juryScoreLabel: 'Jury:',
  showAllRanking: 'Show Full Ranking (Total {count} People)',
  searchPlaceholder: 'Search project title or employee...',
  allCategories: 'All Categories',
  clearFilters: 'Clear Filters',
  noMatchTitle: 'No Glittering Idea Matching Your Search Found',
  noMatchDesc: 'The lights of the showcase are off because there is no \'Glittering Idea\' implemented yet, or no results matched your search.',
  newIdeaBtn: 'Add New Idea',
  otherCategory: 'Other',
  glitteringBadge: 'Glittering Idea (+150 Points)',
  juryScoreBadge: 'Jury Score: {score}/100',
  detailBtn: 'Details',
  benefitLabel: '🎯 Corporate Benefit Provided:',
  guideTitle: 'Scoring Guide',
  guideInnovationTitle: 'What is Innovation Score?',
  guideInnovationDesc1: '• <strong>Approved Idea:</strong> For every approved idea scoring 50+ from the referee <strong>+50 Points</strong>.',
  guideInnovationDesc2: '• <strong>Glittering Idea:</strong> For an idea implemented and showcased <strong>+100 Extra Points</strong> *(Total 150 Points per idea)*.',
  guideJuryTitle: 'What is Jury Score?',
  guideJuryDesc: 'It is the sum of the actual evaluation scores between 0-100 given by Idea Coordinators to the ideas.',
  guideRuleTitle: '3-Tier Ranking & Tie-Breaking Rule:',
  guideRule1: 'The employee with the highest <strong>Total Innovation Score</strong> takes the lead.',
  guideRule2: 'If scores are equal, the one with the higher <strong>Total Referee Jury Scores</strong> takes the lead.',
  guideRule3: 'If jury scores are also equal, the leader is determined by <strong>Manager\'s Choice</strong>.',
  leaderboardTitle: 'General Innovation Leadership Ranking',
  rankCol: 'Rank',
  employeeCol: 'Employee',
  ideaCountCol: 'Idea Count',
  juryScoreCol: 'Jury Score',
  innovationScoreCol: 'Innovation Score',
  ideaCountBadge: '{count} Ideas',
  pointsBadge: '{points} Points',
  sortNewest: '📅 Newest Additions',
  sortHighest: '⭐ Highest Jury Score',
  sortTitle: '🔤 By Title (A-Z)',
  fetchError: 'Error loading showcase data:',
  hiddenUser: '🔒 Hidden Participant',
  innovationLeader: '👑 Innovation Leader',
  glitteringInnovator: '🌟 Glittering Innovator',
  innovativeThinker: '✨ Innovative Thinker'
};

tr.createIdea = {
  fetchError: 'Kategoriler yüklenirken hata:',
  fetchErrorToast: 'Kategoriler yüklenemedi.',
  missingInfo: 'Eksik Bilgi',
  missingInfoDesc: 'Lütfen yıldızlı (*) tüm zorunlu alanları doldurun.',
  success: 'Başarılı',
  error: 'Hata',
  systemError: 'Fikir eklenirken sistemsel bir hata oluştu.',
  pageTitle: '✨ Yeni Fikir Önerisi',
  pageDesc: 'Kurumumuzun geleceğine yön verecek yenilikçi fikrinizi bizimle paylaşın.',
  titleLabel: 'Fikir Başlığı *',
  titlePlaceholder: 'Örn: Müşteri Geri Bildirim Süreçlerinin Yapay Zeka ile Otomasyonu',
  titleHelp: 'Fikrinizi özetleyen net ve dikkat çekici bir başlık girin.',
  categoryLabel: 'Kategori *',
  categoryPlaceholder: '-- Lütfen Bir Kategori Seçin --',
  benefitLabel: 'Amaçlanan Kurumsal Fayda / Kazanım *',
  benefitPlaceholder: 'Bu fikir hayata geçtiğinde ne gibi bir tasarruf, hız veya verimlilik sağlayacak?',
  descLabel: 'Detaylı Açıklama *',
  descPlaceholder: 'Fikrinizin uygulanma adımlarını, yöntemini ve tüm detaylarını açıklayın...',
  filesLabel: 'Ek Dokümanlar / Belgeler (İsteğe Bağlı)',
  fileSelect: 'Dosya Seç',
  fileCancel: 'İptal',
  fileEmpty: 'Dosyaları buraya sürükleyip bırakabilirsiniz.',
  fileHelp: 'Fikrinizi destekleyen PDF, Word, Excel, görsel vb. dosyaları çoklu olarak seçip yükleyebilirsiniz.',
  btnCancel: 'İptal',
  btnDraft: 'Taslak Olarak Kaydet',
  btnSubmit: 'Fikri Havuza At'
};

en.createIdea = {
  fetchError: 'Error loading categories:',
  fetchErrorToast: 'Failed to load categories.',
  missingInfo: 'Missing Information',
  missingInfoDesc: 'Please fill in all mandatory fields marked with an asterisk (*).',
  success: 'Success',
  error: 'Error',
  systemError: 'A system error occurred while adding the idea.',
  pageTitle: '✨ New Idea Proposal',
  pageDesc: 'Share your innovative idea that will shape the future of our institution with us.',
  titleLabel: 'Idea Title *',
  titlePlaceholder: 'e.g., Automation of Customer Feedback Processes with AI',
  titleHelp: 'Enter a clear and catchy title that summarizes your idea.',
  categoryLabel: 'Category *',
  categoryPlaceholder: '-- Please Select a Category --',
  benefitLabel: 'Intended Corporate Benefit / Gain *',
  benefitPlaceholder: 'What kind of savings, speed, or efficiency will this idea provide when implemented?',
  descLabel: 'Detailed Description *',
  descPlaceholder: 'Explain the implementation steps, method, and all details of your idea...',
  filesLabel: 'Additional Documents / Files (Optional)',
  fileSelect: 'Select File',
  fileCancel: 'Cancel',
  fileEmpty: 'You can drag and drop files here.',
  fileHelp: 'You can select and upload multiple files such as PDF, Word, Excel, images, etc. to support your idea.',
  btnCancel: 'Cancel',
  btnDraft: 'Save as Draft',
  btnSubmit: 'Submit to Pool'
};

tr.myIdeas = {
  fetchErrorLog: 'Fikirler yüklenirken hata:',
  fetchErrorToast: 'Fikirler yüklenemedi.',
  success: 'Başarılı',
  error: 'Hata',
  genericError: 'Bir hata oluştu.',
  sortNewest: '📅 En Yeni',
  sortOldest: '📅 En Eski',
  sortTitleAsc: '🔤 Başlık (A-Z)',
  sortTitleDesc: '🔤 Başlık (Z-A)',
  statusDraft: 'Taslak',
  statusGlittering: 'Pırıltılı Fikir',
  statusApproved: 'Olumlu',
  statusRejected: 'Olumsuz',
  statusWithdrawn: 'Geri Çekildi',
  statusPending: 'Bekleyen',
  btnEdit: 'Düzenle',
  btnSubmit: 'Havuza At',
  btnWithdraw: 'Geri Çek',
  btnDetail: 'Detay',
  btnViewDetail: 'Detayları Gör',
  pageTitle: '✨ Fikirlerim',
  pageDesc: 'Sisteme sunduğunuz veya taslak halindeki tüm fikirlerinizi buradan takip edebilirsiniz.',
  filterAll: 'Tüm',
  filterDraft: '📝 Taslak',
  filterPending: '⏳ Bekleyen',
  filterApproved: '✅ Olumlu',
  filterRejected: '❌ Olumsuz',
  newIdeaBtn: 'Yeni Fikir Ekle',
  emptyMessage: 'Bu filtre kriterine uygun bir fikir öneriniz bulunamadı.',
  colTitle: 'Başlık',
  colCategory: 'Kategori',
  colDate: 'Oluşturma Tarihi',
  colStatus: 'Durum',
  colActions: 'İşlemler',
  otherCategory: 'Diğer',
  withdrawTitle: 'Bu ışıltılı hayatı o seçmedi...',
  withdrawConfirmText1: '"',
  withdrawConfirmText2: '" fikrini geri çekmek istediğine gerçekten emin misin?',
  withdrawInfoTitle: 'Aramızdan ayrılan sadece bir taslak, asıl ışıltın hâlâ sende saklı.',
  withdrawInfoDesc: '(Fikriniz değerlendirmeden çekilse dahi sistem arşivinde denetim amacıyla saklanmaya devam eder).',
  btnCancelWithdraw: 'Hala ışığı var. ✨',
  btnConfirmWithdraw: 'Veda vakti geldi. 🪦'
};

en.myIdeas = {
  fetchErrorLog: 'Error loading ideas:',
  fetchErrorToast: 'Failed to load ideas.',
  success: 'Success',
  error: 'Error',
  genericError: 'An error occurred.',
  sortNewest: '📅 Newest',
  sortOldest: '📅 Oldest',
  sortTitleAsc: '🔤 Title (A-Z)',
  sortTitleDesc: '🔤 Title (Z-A)',
  statusDraft: 'Draft',
  statusGlittering: 'Glittering Idea',
  statusApproved: 'Approved',
  statusRejected: 'Rejected',
  statusWithdrawn: 'Withdrawn',
  statusPending: 'Pending',
  btnEdit: 'Edit',
  btnSubmit: 'Submit to Pool',
  btnWithdraw: 'Withdraw',
  btnDetail: 'Details',
  btnViewDetail: 'View Details',
  pageTitle: '✨ My Ideas',
  pageDesc: 'You can track all the ideas you have submitted to the system or drafted here.',
  filterAll: 'All',
  filterDraft: '📝 Draft',
  filterPending: '⏳ Pending',
  filterApproved: '✅ Approved',
  filterRejected: '❌ Rejected',
  newIdeaBtn: 'Add New Idea',
  emptyMessage: 'No idea proposal matching this filter criteria was found.',
  colTitle: 'Title',
  colCategory: 'Category',
  colDate: 'Creation Date',
  colStatus: 'Status',
  colActions: 'Actions',
  otherCategory: 'Other',
  withdrawTitle: 'It didn\'t choose this glittering life...',
  withdrawConfirmText1: '"',
  withdrawConfirmText2: '" are you really sure you want to withdraw this idea?',
  withdrawInfoTitle: 'It\'s just a draft leaving us, your real sparkle is still hidden in you.',
  withdrawInfoDesc: '(Even if your idea is withdrawn from evaluation, it will continue to be kept in the system archive for audit purposes).',
  btnCancelWithdraw: 'It still has light. ✨',
  btnConfirmWithdraw: 'It\'s time to say goodbye. 🪦'
};

tr.ideasList = {
  fetchErrorLog: 'Fikirler yüklenirken hata:',
  unauthorizedToastTitle: 'Yetkisiz Erişim',
  unauthorizedToastDesc: 'Bu sayfayı görüntüleme yetkiniz yok.',
  sortNewest: '📅 En Yeni',
  sortOldest: '📅 En Eski',
  sortScoreDesc: '⭐ En Yüksek Puan',
  sortScoreAsc: '⭐ En Düşük Puan',
  sortTitleAsc: '🔤 Başlık (A-Z)',
  sortTitleDesc: '🔤 Başlık (Z-A)',
  hiddenUser: '🔒 Gizli Katılımcı',
  anonymous: 'Anonim (Kör Değerlendirme)',
  you: '(Siz)',
  statusGlittering: 'Pırıltılı Fikir',
  statusApproved: 'Olumlu',
  statusRejected: 'Olumsuz',
  statusPending: 'Bekleyen',
  btnReview: 'İncele',
  btnReviewRate: 'İncele / Puanla',
  pageTitle: '✨ Fikir ve Öneriler',
  pageDesc: 'Kurum çalışanları tarafından sunulan tüm inovasyon önerilerini inceleyin ve puanlayın.',
  filterAll: 'Tüm',
  filterPending: '⏳ Bekleyen',
  filterApproved: '✅ Olumlu',
  filterRejected: '❌ Olumsuz',
  emptyMessage: 'Bu filtre kriterine uygun bir fikir önerisi bulunamadı.',
  colAuthor: 'Fikir Sahibi',
  colTitle: 'Fikir Başlığı',
  colCategory: 'Kategori',
  colDate: 'Tarih',
  colStatus: 'Durum',
  colActions: 'İşlemler',
  otherCategory: 'Diğer'
};

en.ideasList = {
  fetchErrorLog: 'Error loading ideas:',
  unauthorizedToastTitle: 'Unauthorized Access',
  unauthorizedToastDesc: 'You do not have permission to view this page.',
  sortNewest: '📅 Newest',
  sortOldest: '📅 Oldest',
  sortScoreDesc: '⭐ Highest Score',
  sortScoreAsc: '⭐ Lowest Score',
  sortTitleAsc: '🔤 Title (A-Z)',
  sortTitleDesc: '🔤 Title (Z-A)',
  hiddenUser: '🔒 Hidden Participant',
  anonymous: 'Anonymous (Blind Evaluation)',
  you: '(You)',
  statusGlittering: 'Glittering Idea',
  statusApproved: 'Approved',
  statusRejected: 'Rejected',
  statusPending: 'Pending',
  btnReview: 'Review',
  btnReviewRate: 'Review / Rate',
  pageTitle: '✨ Ideas and Suggestions',
  pageDesc: 'Examine and rate all innovation suggestions submitted by institution employees.',
  filterAll: 'All',
  filterPending: '⏳ Pending',
  filterApproved: '✅ Approved',
  filterRejected: '❌ Rejected',
  emptyMessage: 'No idea proposal matching this filter criteria was found.',
  colAuthor: 'Idea Owner',
  colTitle: 'Idea Title',
  colCategory: 'Category',
  colDate: 'Date',
  colStatus: 'Status',
  colActions: 'Actions',
  otherCategory: 'Other'
};

fs.writeFileSync(trPath, JSON.stringify(tr, null, 2), 'utf8');
fs.writeFileSync(enPath, JSON.stringify(en, null, 2), 'utf8');
console.log('JSON files updated.');
